name: DigIntoTheWord
favicon: null
layout_spectrum: 0.26591
typography_spectrum: 0.66591
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e4e5'
    - '#5a5744'
    - '#bea974'
    - '#1f2022'
    - '#bc584c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
